### ISSUE TITLE
would it make sense to automatically group unit tests by the endpoint that they test?

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-Monitoring-Dashboard#42]
i'd like to talk about this in our next meeting

**Comment by kloostert** [comment]
The most recent commit in the development branch contains an implementation of the functionality for unit test results grouping by the endpoints that they hit. Running the Dashboard on a very simple app results in the following 'Test Monitor' page:
<img width="1276" alt="screenshot" src="https://user-images.githubusercontent.com/17165311/31434894-14581806-ae7e-11e7-93b4-4a17a16177d1.png">
It shows two simple endpoints, with their corresponding color in the header.
On clicking the header, the unit test results for that specific endpoint are shown (like for 'static').
Is this more or less what you had in mind?

**Comment by mircealungu** [comment]
that is cool @kloostert !

do i have to migrate the DB/code in any way
to try it out on the server? or can i simply 
pull the latest version on the dev branch? 

what are main and static in the image? 

the run-times in the table ... are they 
for the test or for the endpoint?

**Comment by kloostert** [comment]
Migration of the DB should be done automatically by the code. 

But, when running the dashboard of the development branch on the server, the 'Test Monitor' page will be inaccessible, since it will not yet have any grouped unit test data (which it should receive from Travis).
Maybe it's an idea to set up the Travis part first, such that this data can be provided?

In the image, 'main' and 'static' are endpoint names of the small Flask app that I used for testing purposes.

The run-times in the table are left untouched and so they are the same as before (those are execution times for the tests).

**Comment by kloostert** [comment]
I can do the Travis setup and configuration for this new functionality, but it seems that the current build of Zeeguu-API is not able to get through the setup phase. The Travis log says:
`error: newspaper3k 0.2.5 is installed but newspaper3k==0.2.2 is required by {'watchmen'}`
`The command "python setup.py develop" failed and exited with 1 during .`

**Comment by mircealungu** [comment]
thanks Thijs!
let me look into that!

m.

**Comment by FlyingBird95** [comment]
Is this issue resolved now? @mircealungu @kloostert

**Comment by mircealungu** [comment]
Indeed.
